In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns",None)

In [3]:
sample_df=pd.read_csv(
    "../data/processed/us_accidents_sample.csv"
)

sample_df.shape

(500000, 46)

In [4]:
columns_to_drop=[
    "ID",
    "Country",
    "Turning_Loop",
    "End_Lat",
    'End_Lng',
    "Description",
    "Street",
    "Zipcode"
]

In [5]:
sample_df.isnull().sum()

ID                            0
Source                        0
Severity                      0
Start_Time                    0
End_Time                      0
Start_Lat                     0
Start_Lng                     0
End_Lat                  220676
End_Lng                  220676
Distance(mi)                  0
Description                   1
Street                      733
City                         15
County                        0
State                         0
Zipcode                     103
Country                       0
Timezone                    486
Airport_Code               1445
Weather_Timestamp          7723
Temperature(F)            10548
Wind_Chill(F)            129475
Humidity(%)               11230
Pressure(in)               9054
Visibility(mi)            11406
Wind_Direction            11346
Wind_Speed(mph)           37090
Precipitation(in)        142799
Weather_Condition         11142
Amenity                       0
Bump                          0
Crossing                      0
Give_Way                      0
Junction                      0
No_Exit                       0
Railway                       0
Roundabout                    0
Station                       0
Stop                          0
Traffic_Calming               0
Traffic_Signal                0
Turning_Loop                  0
Sunrise_Sunset             1540
Civil_Twilight             1540
Nautical_Twilight          1540
Astronomical_Twilight      1540
dtype: int64

In [6]:
sample_df.shape

(500000, 46)

In [7]:
sample_df.to_csv(
    "../data/processed/us_accidents_cleaned.csv",
    index=False
)

In [8]:
sample_df.shape

(500000, 46)

# Data Preprocessing

## Objective

The goal of this notebook is to prepare the dataset for machine learning by:

- Removing irrelevant features
- Handling missing values
- Converting data types
- Creating model-ready data

In [9]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 46 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     500000 non-null  object
 1   Source                 500000 non-null  object
 2   Severity               500000 non-null  int64
 3   Start_Time             500000 non-null  object
 4   End_Time               500000 non-null  object
 5   Start_Lat              500000 non-null  float64
 6   Start_Lng              500000 non-null  float64
 7   End_Lat                279324 non-null  float64
 8   End_Lng                279324 non-null  float64
 9   Distance(mi)           500000 non-null  float64
 10  Description            499999 non-null  object
 11  Street                 499267 non-null  object
 12  City                   499985 non-null  object
 13  County                 500000 non-null  object
 14  State                  500000 non-null  object
 15  Zipcode                499897 non-null  object
 16  Country                500000 non-null  object
 17  Timezone               499514 non-null  object
 18  Airport_Code           498555 non-null  object
 19  Weather_Timestamp      492277 non-null  object
 20  Temperature(F)         489452 non-null  float64
 21  Wind_Chill(F)          370525 non-null  float64
 22  Humidity(%)            488770 non-null  float64
 23  Pressure(in)           490946 non-null  float64
 24  Visibility(mi)         488594 non-null  float64
 25  Wind_Direction         488654 non-null  object
 26  Wind_Speed(mph)        462910 non-null  float64
 27  Precipitation(in)      357201 non-null  float64
 28  Weather_Condition      488858 non-null  object
 29  Amenity                500000 non-null  bool
 30  Bump                   500000 non-null  bool
 31  Crossing               500000 non-null  bool
 32  Give_Way               500000 non-null  bool
 33  Junction               500000 non-null  bool
 34  No_Exit                500000 non-null  bool
 35  Railway                500000 non-null  bool
 36  Roundabout             500000 non-null  bool
 37  Station                500000 non-null  bool
 38  Stop                   500000 non-null  bool
 39  Traffic_Calming        500000 non-null  bool
 40  Traffic_Signal         500000 non-null  bool
 41  Turning_Loop           500000 non-null  bool
 42  Sunrise_Sunset         498460 non-null  object
 43  Civil_Twilight         498460 non-null  object
 44  Nautical_Twilight      498460 non-null  object
 45  Astronomical_Twilight  498460 non-null  object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 132.1+ MB

In [10]:
sample_df.isnull().sum().sort_values(ascending=False)

End_Lat                  220676
End_Lng                  220676
Precipitation(in)        142799
Wind_Chill(F)            129475
Wind_Speed(mph)           37090
Visibility(mi)            11406
Wind_Direction            11346
Humidity(%)               11230
Weather_Condition         11142
Temperature(F)            10548
Pressure(in)               9054
Weather_Timestamp          7723
Nautical_Twilight          1540
Civil_Twilight             1540
Sunrise_Sunset             1540
Astronomical_Twilight      1540
Airport_Code               1445
Street                      733
Timezone                    486
Zipcode                     103
City                         15
Description                   1
Traffic_Signal                0
Roundabout                    0
Station                       0
Stop                          0
Traffic_Calming               0
Country                       0
Turning_Loop                  0
No_Exit                       0
End_Time                      0
Start_Time                    0
Severity                      0
Railway                       0
Crossing                      0
Junction                      0
Give_Way                      0
Bump                          0
Amenity                       0
Start_Lat                     0
Start_Lng                     0
Distance(mi)                  0
Source                        0
County                        0
State                         0
ID                            0
dtype: int64

In [11]:
columns_to_drop = [
    "ID",
    "Country",
    "Turning_Loop",
    "End_Lat",
    "End_Lng",
    "Description",
    "Street",
    "Zipcode"
]

In [13]:
sample_df=sample_df.drop(
    columns=columns_to_drop
)

In [14]:
sample_df.shape

(500000, 38)

In [15]:
sample_df.columns.tolist()

['Source',
 'Severity',
 'Start_Time',
 'End_Time',
 'Start_Lat',
 'Start_Lng',
 'Distance(mi)',
 'City',
 'County',
 'State',
 'Timezone',
 'Airport_Code',
 'Weather_Timestamp',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Direction',
 'Wind_Speed(mph)',
 'Precipitation(in)',
 'Weather_Condition',
 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',
 'Sunrise_Sunset',
 'Civil_Twilight',
 'Nautical_Twilight',
 'Astronomical_Twilight']

In [16]:
missing_report = pd.DataFrame({
    "Missing Values": sample_df.isnull().sum(),
    "Percentage": round(
        sample_df.isnull().sum() / len(sample_df) * 100,
        2
    )
})

missing_report = missing_report.sort_values(
    by="Percentage",
    ascending=False
)

missing_report[missing_report["Missing Values"] > 0]

                       Missing Values  Percentage
Precipitation(in)              142799       28.56
Wind_Chill(F)                  129475       25.90
Wind_Speed(mph)                 37090        7.42
Visibility(mi)                  11406        2.28
Wind_Direction                  11346        2.27
Humidity(%)                     11230        2.25
Weather_Condition               11142        2.23
Temperature(F)                  10548        2.11
Pressure(in)                     9054        1.81
Weather_Timestamp                7723        1.54
Nautical_Twilight                1540        0.31
Civil_Twilight                   1540        0.31
Sunrise_Sunset                   1540        0.31
Astronomical_Twilight            1540        0.31
Airport_Code                     1445        0.29
Timezone                          486        0.10
City                               15        0.00

In [17]:
numerical_cols = sample_df.select_dtypes(
    include=["int64", "float64"]
).columns

numerical_cols

Index(['Severity', 'Start_Lat', 'Start_Lng', 'Distance(mi)', 'Temperature(F)',
       'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)',
       'Wind_Speed(mph)', 'Precipitation(in)'],
      dtype='object')

In [18]:
categorical_cols = sample_df.select_dtypes(
    include=["object"]
).columns

categorical_cols

Index(['Source', 'Start_Time', 'End_Time', 'City', 'County', 'State',
       'Timezone', 'Airport_Code', 'Weather_Timestamp', 'Wind_Direction',
       'Weather_Condition', 'Sunrise_Sunset', 'Civil_Twilight',
       'Nautical_Twilight', 'Astronomical_Twilight'],
      dtype='object')

In [20]:
missing_report[missing_report["Missing Values"] > 0]

                       Missing Values  Percentage
Precipitation(in)              142799       28.56
Wind_Chill(F)                  129475       25.90
Wind_Speed(mph)                 37090        7.42
Visibility(mi)                  11406        2.28
Wind_Direction                  11346        2.27
Humidity(%)                     11230        2.25
Weather_Condition               11142        2.23
Temperature(F)                  10548        2.11
Pressure(in)                     9054        1.81
Weather_Timestamp                7723        1.54
Nautical_Twilight                1540        0.31
Civil_Twilight                   1540        0.31
Sunrise_Sunset                   1540        0.31
Astronomical_Twilight            1540        0.31
Airport_Code                     1445        0.29
Timezone                          486        0.10
City                               15        0.00

In [21]:
numerical_missing = [
    "Precipitation(in)",
    "Wind_Chill(F)",
    "Wind_Speed(mph)",
    "Visibility(mi)",
    "Humidity(%)",
    "Temperature(F)",
    "Pressure(in)"
]

In [22]:
for col in numerical_missing:
    sample_df[col].fillna(
        sample_df[col].median(),
        inplace=True
    )

/var/folders/9n/74n8vgqd7pj3k9gsx2fzb2h80000gn/T/ipykernel_75256/1408900106.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample_df[col].fillna(
/var/folders/9n/74n8vgqd7pj3k9gsx2fzb2h80000gn/T/ipykernel_75256/1408900106.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample_df[col].fillna(
/var/folders/9n/74n8vgqd7pj3k9gsx2fzb2h80000gn/T/ipykernel_75256/1408900106.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample_df[col].fillna(
/var/folders/9n/74n8vgqd7pj3k9gsx2fzb2h80000gn/T/ipykernel_75256/1408900106.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample_df[col].fillna(
/var/folders/9n/74n8vgqd7pj3k9gsx2fzb2h80000gn/T/ipykernel_75256/1408900106.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample_df[col].fillna(
/var/folders/9n/74n8vgqd7pj3k9gsx2fzb2h80000gn/T/ipykernel_75256/1408900106.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample_df[col].fillna(
/var/folders/9n/74n8vgqd7pj3k9gsx2fzb2h80000gn/T/ipykernel_75256/1408900106.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample_df[col].fillna(

In [23]:
categorical_missing = [
    "Wind_Direction",
    "Weather_Condition",
    "Airport_Code",
    "Timezone",
    "City",
    "Sunrise_Sunset",
    "Civil_Twilight",
    "Nautical_Twilight",
    "Astronomical_Twilight"
]

In [24]:
for col in categorical_missing:
    sample_df[col].fillna(
        sample_df[col].mode()[0],
        inplace=True
    )

/var/folders/9n/74n8vgqd7pj3k9gsx2fzb2h80000gn/T/ipykernel_75256/2049749821.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample_df[col].fillna(

In [25]:
sample_df["Weather_Timestamp"].fillna(
    sample_df["Start_Time"],
    inplace=True
)

/var/folders/9n/74n8vgqd7pj3k9gsx2fzb2h80000gn/T/ipykernel_75256/3450694707.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample_df["Weather_Timestamp"].fillna(

In [26]:
sample_df.isnull().sum().sort_values(
    ascending=False
).head(10)

Source               0
Railway              0
Weather_Condition    0
Amenity              0
Bump                 0
Crossing             0
Give_Way             0
Junction             0
No_Exit              0
Roundabout           0
dtype: int64

In [27]:
sample_df.to_csv(
    "../data/processed/us_accidents_cleaned.csv",
    index=False
)

In [28]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 38 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Source                 500000 non-null  object
 1   Severity               500000 non-null  int64
 2   Start_Time             500000 non-null  object
 3   End_Time               500000 non-null  object
 4   Start_Lat              500000 non-null  float64
 5   Start_Lng              500000 non-null  float64
 6   Distance(mi)           500000 non-null  float64
 7   City                   500000 non-null  object
 8   County                 500000 non-null  object
 9   State                  500000 non-null  object
 10  Timezone               500000 non-null  object
 11  Airport_Code           500000 non-null  object
 12  Weather_Timestamp      500000 non-null  object
 13  Temperature(F)         500000 non-null  float64
 14  Wind_Chill(F)          500000 non-null  float64
 15  Humidity(%)            500000 non-null  float64
 16  Pressure(in)           500000 non-null  float64
 17  Visibility(mi)         500000 non-null  float64
 18  Wind_Direction         500000 non-null  object
 19  Wind_Speed(mph)        500000 non-null  float64
 20  Precipitation(in)      500000 non-null  float64
 21  Weather_Condition      500000 non-null  object
 22  Amenity                500000 non-null  bool
 23  Bump                   500000 non-null  bool
 24  Crossing               500000 non-null  bool
 25  Give_Way               500000 non-null  bool
 26  Junction               500000 non-null  bool
 27  No_Exit                500000 non-null  bool
 28  Railway                500000 non-null  bool
 29  Roundabout             500000 non-null  bool
 30  Station                500000 non-null  bool
 31  Stop                   500000 non-null  bool
 32  Traffic_Calming        500000 non-null  bool
 33  Traffic_Signal         500000 non-null  bool
 34  Sunrise_Sunset         500000 non-null  object
 35  Civil_Twilight         500000 non-null  object
 36  Nautical_Twilight      500000 non-null  object
 37  Astronomical_Twilight  500000 non-null  object
dtypes: bool(12), float64(10), int64(1), object(15)
memory usage: 104.9+ MB

## Missing Value Treatment

Missing values were handled using the following strategy:

### Numerical Features
Missing values were replaced using the median value of each feature.

### Categorical Features
Missing values were replaced using the most frequent category (mode).

### Datetime Features
Missing values in Weather_Timestamp were replaced using Start_Time.

After preprocessing, the dataset contained no missing values.## Missing Value Treatment

Missing values were handled using the following strategy:

### Numerical Features
Missing values were replaced using the median value of each feature.

### Categorical Features
Missing values were replaced using the most frequent category (mode).

### Datetime Features
Missing values in Weather_Timestamp were replaced using Start_Time.

After preprocessing, the dataset contained no missing values.

In [29]:
sample_df.isnull().sum().sum()

np.int64(0)

In [30]:
sample_df.to_csv(
    "../data/processed/us_accidents_cleaned.csv",
    index=False
)

In [31]:
sample_df.shape

(500000, 38)